server:
  port: 8082
databases:
  - user: admin
    passwrod: admin
    host: localhost
    dbName: test
  - user: client
    passwrod: client
    host: localhost
    dbName: test
security:
  jwt:
    key: test